apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - image: flask:TAG
        name: flask
        ports:
        - containerPort: 5000
